name: Release

on:
  workflow_dispatch:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

jobs:
  release:
    name: Build for ${{ matrix.os_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os_name: FreeBSD-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-freebsd
          - os_name: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-musl
          - os_name: Linux-aarch64
            os: ubuntu-20.04
            target: aarch64-unknown-linux-musl
          - os_name: Linux-arm
            os: ubuntu-20.04
            target: arm-unknown-linux-musleabi
          - os_name: Linux-riscv64
            os: ubuntu-20.04
            target: riscv64gc-unknown-linux-gnu
          - os_name: Windows-aarch64
            os: windows-latest
            target: aarch64-pc-windows-msvc
            ext: ".exe"
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: ".exe"
          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
          - os_name: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Install musl-tools on Linux
        run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools
        if: contains(matrix.name, 'musl')
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.target }}
          toolchain: stable
          args: "--locked --release"
          strip: true
      - name: Rename Artifacts
        shell: bash
        run: |
          APP_NAME={{APP_NAME}}
          ver=${GITHUB_REF#refs/tags/}
          ASSET_PATH=$APP_NAME-$ver-${{ matrix.target }}${{ matrix.ext }}
          mv target/${{ matrix.target }}/release/$APP_NAME $ASSET_PATH
          echo "ASSET_PATH=$ASSET_PATH" >> $GITHUB_ENV
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: ${{ env.ASSET_PATH }}
          # body_path: Changes.md
